### ISSUE TITLE
Port SavingsManager contracts from `master` to `master-v2`

### ISSUE THREAD

**Issue by alsco77** [mstable/mStable-contracts#135]
**Is your feature request related to a problem? Please describe.**
Recently this repo was ported from solc 0.5.16 to 0.8.x, and truffle/web3.js to hardhat/ethers.js.

There are a number of contracts that have not yet been migrated, and will be used in future product releases.

**Describe the solution you'd like**
This issue proposes that the `SavingsManager.sol` is ported from `master` to `master-v2`. This includes:
- porting of the solidity file and all dependencies
- refactoring to bring code in line with solc 0.8 (e.g. removal of SafeMath)
- porting of relevant test cases to new repo (TestSavingsManager.spec.ts)

**Comment by doncesarts** [comment]
I think this is already done by https://github.com/mstable/mStable-contracts/pull/167 ? Is not it ? @alsco77

**Comment by alsco77** [comment]
Ah yes, good catch @doncesarts , some of these issues are ood
