### ISSUE TITLE
Port StakingRewards contracts from `master` to `master-v2`

### ISSUE THREAD

**Issue by alsco77** [mstable/mStable-contracts#136]
**Is your feature request related to a problem? Please describe.**
Recently this repo was ported from solc 0.5.16 to 0.8.x, and truffle/web3.js to hardhat/ethers.js.

There are a number of contracts that have not yet been migrated, and will be used in future product releases.

**Describe the solution you'd like**
This issue proposes that the `StakingRewards.sol` is ported from `master` to `master-v2`. This includes:
- porting of the solidity file and all dependencies
- refactoring to bring code in line with solc 0.8 (e.g. removal of SafeMath)
- porting of relevant test cases to new repo (TestSavingsManager.spec.ts)

**Comment by doncesarts** [comment]
It is already ported by https://github.com/mstable/mStable-contracts/commit/4d9598701a672ea92cc2c047f5b1e4baccd7aa75
