### ISSUE TITLE
Port Nexus contracts from `master` to `master-v2`

### ISSUE THREAD

**Issue by alsco77** [mstable/mStable-contracts#139]
**Is your feature request related to a problem? Please describe.**
Recently this repo was ported from solc 0.5.16 to 0.8.x, and truffle/web3.js to hardhat/ethers.js.

There are a number of contracts that have not yet been migrated, and will be used in future product releases.

**Describe the solution you'd like**
This issue proposes that the `Nexus.sol` is ported from `master` to `master-v2`. This includes:
- porting of the solidity file and all dependencies
- refactoring to bring code in line with solc 0.8 (e.g. removal of SafeMath)
- porting of relevant test cases to new repo (TestSavingsManager.spec.ts)

**Comment by doncesarts** [comment]
It is already ported by  https://github.com/mstable/mStable-contracts/commit/928bdc77ea1812743f76a08084d036ab23125c45#diff-e1f41bcb08419f96d4449bc75d0a2d1476d977313209837020b7eae7d929efbf
Or is there something else missing ?
