### ISSUE TITLE
Unliquidator

### ISSUE THREAD

**Issue by rafaelugolini** [mstable/mStable-contracts#333]
MIP 26 vote was passed. We should stop liquidating COMP and stkAave rewards. A contract to claim and send the rewards to the Treasury is specified in https://mips.mstable.org/MIPS/mip-26.html

- [x] To add test coverage to Unliquidator Smart Contract 
- [x] Deploy the Unliquidator to mainnet
- [x] Protocol DAO propose new `Liquidator` module in the Nexus to new Unliquidator contract
- [x] After a week Protocol DAO accepts new `Liquidator` module
- [x] Each integration contract approves the new Unliquidator contract
  - [x] Aave mUSD used by USDT, sUSD and DAI
  - [x] Compound mUSD used by USDC
  - [x] Aave mBTC used by WBTC
  - [x] Aave BUSD Feeder Pool
  - [x] Aave RAI Feeder Pool
- [x] Execute first claim for each integration contract

**Comment by doncesarts** [comment]
Current PR https://github.com/mstable/mStable-contracts/pull/331 , I added some comments on it.

**Comment by naddison36** [comment]
Deploying Unliquidator contract with hash 0xfad2121af11edef138788ff03e0ef54dedac67869be33f5dee90e90cf789d69d from 0xb81473f20818225302b8fffb905b53d58a793d84 with gas price 27.3 Gwei
Deployed Unliquidator to 0xC643B9D66C68d06EA844251a441A0a1211E60656 in block 14306896, using 651613 gas costing 0.0177890349 ETH

**Comment by naddison36** [comment]
Protocol DAO tx 267. Change Liquidator module in Nexus to newly deployed Unliquidator contract 0xC643B9D66C68d06EA844251a441A0a1211E60656 so COMP and stkAAVE are sent to treasury rather than liquidated

**Comment by naddison36** [comment]
267 fail as it ran out of gas. The safeTxGas was only 36,981 for some reason. When I execute it as a fork it uses 72,952  gas. I've reraised the tx and it has estimate the safeTxGas at 90,071 which should be plenty.
273. Change Liquidator module in Nexus to newly deployed Unliquidator contract 0xC643B9D66C68d06EA844251a441A0a1211E60656 so COMP and stkAAVE are sent to treasury rather than liquidated

**Comment by naddison36** [comment]
Protocol DAO tx 273 to propose the `Liquidator` module in the Nexus be changed to the `Unliquidator` contract has been executed https://etherscan.io/tx/0xf9e3cd04e22394294006787ec609983e4b9591de6fa69bcba1480dae758c625d

A new Protocol DAO tx to accept this proposal can be raised on Tuesday, 15 March.

**Comment by naddison36** [comment]
280. Accept proposed Nexus model upgraded of Liquidator to new Unliquidator contract. This will allow COMP and stkAAVE to be sent to Treasury rather than be liquidated

**Comment by naddison36** [comment]
We have another example of the `safeTxGas` being set too low by Gnosis Safe. According to Gnosis Safe docs this should not happen when using their UI but it is. I've raised the issue in a Gnosis <> mStable TG channel we have.

I'm executing 280 with a low gas price as that's quicker than getting it rejected. The inner tx while fail with "Out of Gas".
I've raised 281 to replace 280 which did set enough gas to execute.

**Comment by naddison36** [comment]
Protocol DAO txs so each integration contract approves the new Unliquidator contract
287. mUSD Aave V2 integration approves Unliquidator
288. mUSD Compound integration approves Unliquidator
289. mBTC Aave V2 integration approves Unliquidator
290. BUSD Feeder Pool Aave integration approves Unliquidator
291. RAI Feeder Pool Aave integration approves Unliquidator

**Comment by naddison36** [comment]
All the integration contract approvals have been executed

**Comment by naddison36** [comment]
Tested claiming COMP and stkAAVE for treasury with new Unliquidator contract
- 225 COMP from USDC https://etherscan.io/tx/0x3dcf7bb971959b5f55f353712395cf866af581e285bf73d500e423141e7668d6
- 84.4 stkAAVE from USDT https://etherscan.io/tx/0x2184aaaaad5a5eaab1faa6b51b7b258204cb9ec027d5ed69ef1ae9a9103f40b1
- 9.8 stkAAVE from BUSD https://etherscan.io/tx/0x2cd053cad97896b49d299e58c5e701e12aae64f07d9eb3a9d75d09233ca66797 
- 6.9 stkAAVE from RAI https://etherscan.io/tx/0xe73b8092a8b96687aedbc2b380cf669ec4e98923cf1cf0434d2b700a8ac80b9e 

The COMP and stkAAVE have been sent to the Treasury subDAO https://etherscan.io/address/0x3dd46846eed8d147841ae162c8425c08bd8e1b41
