### ISSUE TITLE
Emissions Controller: update with Linear function and upgrade contract

### ISSUE THREAD

**Issue by dimsome** [mstable/mStable-contracts#374]
- [x] Adjust the function `topLineEmission` in the EmissionController.sol to reflect the linear emissions function: https://forum.mstable.org/t/mccp-24-reduce-weekly-mta-emissions/912
- [x] Update tests
- [x] Update hardhat tasks
- [x] Let MCCP 24 pass in governance
- [x] Propose contract upgrade
- [x] Accept contract upgrade

**Comment by doncesarts** [comment]
Hi @jkusne , could you please attach the expected emission details to double check the calculations ? 
It could be a sample of emissions like  [1, 8, 100, 306, 611, 612]

**Comment by jkusne** [comment]
The actual total number of epochs is 624, not 612 as it is wrongly stated in the MCCP. I made a mistake when typing the MCCP. The current number of total epochs es 312, which corresponds to 6 years, so the new number of epochs should be the double of that, which is 624. This way, we would have exactly 12 years of emissions, and the last epoch would emit 0 (as it is supposed to be).

**Comment by doncesarts** [comment]
- [ ] New implementation deployed https://etherscan.io/address/0x48A91EB6D623bBc1b9c350dC40a671E72e1D4cdd
```
yarn task --network mainnet deploy-emissions --deploy-proxy "false"
```
- [ ] Contract Verified

**Comment by dimsome** [comment]
@jkusne please update the MCCP in GitHub and forum with the correct number

**Comment by doncesarts** [comment]
Proposal accepted https://etherscan.io/tx/0x0047e5229d0839b697a86334476d6c2f4bd0e037b31ab51ae96792ae55f3075e
