### ISSUE TITLE
Deploy on rinkeby

### ISSUE THREAD

**Issue by fritzschoff** [mstable/mStable-contracts#97]
I guess this issue is more for the backlog, but it would be nice to have an instance running on the rinkeby test network.

**Comment by alsco77** [comment]
Thanks @fritzschoff 

FWIW - This should be as simple as adding Rinkeby deployment details (from Compound/Aave) in `test-utils/constants`, then adding to the migration files. Then the deployed addresses could be added to mStable-docs && mStables-subgraph.
